import type { Metadata } from "next";
import { Cinzel, Mea_Culpa, Montserrat } from "next/font/google";
import "./globals.css";

const herrVonMuellerhoff = Mea_Culpa({
  variable: "--font-herr-von-muellerhoff",
  weight: '400',
  subsets: ["latin"],
});

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${herrVonMuellerhoff.variable} ${montserrat.variable} antialiased`}
        suppressHydrationWarning
        suppressContentEditableWarning
      >
        {children}
      </body>
    </html>
  );
}
